server {
    listen 80;
    listen [::]:80;
    server_name virtualpet.beer www.virtualpet.beer;

    root /var/www/virtualpet.beer;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(gif|png|jpg|jpeg|css|js|ico|svg|webp)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
